In [5]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns



# Scaler and Built In **Functions**


In [15]:
scalar = 3.7
arr = np.array([1,2,3,4,5,6])


sin_values= np.sin(arr)
cos_values= np.cos(arr)
tan_values= np.tan(arr)
asin_values = np.arcsin(np.clip(arr/np.max(arr), -1, 1))
acos_values = np.arccos(np.clip(arr/np.max(arr), -1, 1))
atan_values = np.arctan(arr)

exp_values= np.exp(arr)
log_values= np.exp(arr)

rem_values= np.remainder(arr,2)

round_values = np.round(arr)
floor_values = np.floor(arr)
ceil_values = np.ceil(arr)
trunc_values =np.trunc(arr)


print("sin:",sin_values)
print("cos:",cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:",acos_values)
print("atan:",atan_values)
print("exp:", exp_values)
print("log:", log_values)
print("Remainder:", rem_values)
print("Round:", round_values)
print("floor:", floor_values)
print("ceil:", ceil_values)
print("trunc:", trunc_values)





sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
tan: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]
asin: [0.16744808 0.33983691 0.52359878 0.72972766 0.98511078 1.57079633]
acos: [1.40334825 1.23095942 1.04719755 0.84106867 0.58568554 0.        ]
atan: [0.78539816 1.10714872 1.24904577 1.32581766 1.37340077 1.40564765]
exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
log: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
Remainder: [1 0 1 0 1 0]
Round: [1 2 3 4 5 6]
floor: [1. 2. 3. 4. 5. 6.]
ceil: [1. 2. 3. 4. 5. 6.]
trunc: [1. 2. 3. 4. 5. 6.]


# 3X2 **matrix**

In [20]:
matrix = np.array([[1,2],[2,3],[3,4]])



sin_values= np.sin(matrix)
cos_values= np.cos(matrix)
tan_values= np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix/np.max(matrix), -1, 1))
acos_values = np.arccos(np.clip(matrix/np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

exp_values= np.exp(matrix)
log_values= np.exp(matrix)

rem_values= np.remainder(matrix,2)

round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)
trunc_values =np.trunc(matrix)


print("sin:",sin_values)
print("cos:",cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:",acos_values)
print("atan:",atan_values)
print("exp:", exp_values)
print("log:", log_values)
print("Remainder:", rem_values)
print("Round:", round_values)
print("floor:", floor_values)
print("ceil:", ceil_values)
print("trunc:", trunc_values)



sin: [[ 0.84147098  0.90929743]
 [ 0.90929743  0.14112001]
 [ 0.14112001 -0.7568025 ]]
cos: [[ 0.54030231 -0.41614684]
 [-0.41614684 -0.9899925 ]
 [-0.9899925  -0.65364362]]
tan: [[ 1.55740772 -2.18503986]
 [-2.18503986 -0.14254654]
 [-0.14254654  1.15782128]]
asin: [[0.25268026 0.52359878]
 [0.52359878 0.84806208]
 [0.84806208 1.57079633]]
acos: [[1.31811607 1.04719755]
 [1.04719755 0.72273425]
 [0.72273425 0.        ]]
atan: [[0.78539816 1.10714872]
 [1.10714872 1.24904577]
 [1.24904577 1.32581766]]
exp: [[ 2.71828183  7.3890561 ]
 [ 7.3890561  20.08553692]
 [20.08553692 54.59815003]]
log: [[ 2.71828183  7.3890561 ]
 [ 7.3890561  20.08553692]
 [20.08553692 54.59815003]]
Remainder: [[1 0]
 [0 1]
 [1 0]]
Round: [[1 2]
 [2 3]
 [3 4]]
floor: [[1. 2.]
 [2. 3.]
 [3. 4.]]
ceil: [[1. 2.]
 [2. 3.]
 [3. 4.]]
trunc: [[1. 2.]
 [2. 3.]
 [3. 4.]]


# Vector **Functions**

In [23]:
vec=np.array([[3.2,2.1,1.1],[4.2,2.3,2.2]])

max_value = np.max(vec)
max_index = np.argmax(vec)

min_value = np.min(vec)
min_index = np.argmin(vec)


vec_length = len(vec)


sorted_vec = np.sort(vec)

sum_values = np.sum(vec)

prod_values = np.prod(vec)

median_value = np.median(vec)

mean_value = np.mean(vec)

std_dev = np.std(vec)


rowwise_desc = -np.sort(-vec, axis=1)

sorted_flat = np.sort(vec.flatten())[::-1]
sorted_matrix = sorted_flat.reshape(vec.shape)


print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)
print("Row-wise descending:\n", rowwise_desc)
print("Entire matrix descending:\n", sorted_matrix)



Max value: 4.2 at index 3
Min value: 1.1 at index 2
Length of vector: 2
Sorted vector: [[1.1 2.1 3.2]
 [2.2 2.3 4.2]]
Sum of elements: 15.100000000000001
Product of elements: 157.09478400000003
Median value: 2.25
Mean value: 2.516666666666667
Standard deviation: 0.9685326817178426
Row-wise descending:
 [[3.2 2.1 1.1]
 [4.2 2.3 2.2]]
Entire matrix descending:
 [[4.2 3.2 2.3]
 [2.2 2.1 1.1]]
